adv: False
contrastive: True

watermark:
  length: 15


optimize:
  lr: 0.0007
  lambda_e: 1.0
  lambda_m: 0.0001
  lambda_cl: 0.002
  lambda_a: 0.01
  batch_size: 4
  step_size: 4 # large value means do not decay
  gamma: 0.85
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.00001
  grad_clip_thresh: 1.0
  grad_acc_step: 8
  up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
  lr_disc: 0.00002
  alpha: 10

contrastive_loss: info_nce

iter:
  epoch: 20
  # epoch: 100
  save_circle: 5
  show_circle: 100
  val_circle: 100
