dim:
  embedding: 128   # suitable transformer embedding dimension

layer:
  nlayers_encoder: 3
  nlayers_decoder: 3

audio:
  win_dim: 256     # <--- ADD this to reflect input window dimension

conv2:
  block: 'skip' #'skip', 'relu'
  layers_CE: 3
  layers_EM: 3
  hidden_dim: 64