dim:
  embedding: 128   # suitable transformer embedding dimension

audio:
  win_dim: 256     # <--- ADD this to reflect input window dimension

conv2:
  block: 'relu' #'skip', 'relu'
  nlayers_encoder: 2
  nlayers_embedder: 2
  nlayers_decoder: 4
  hidden_dim: 128
