dim:
  embedding: 128   # suitable transformer embedding dimension

layer:
  nlayers_encoder: 2
  nlayers_decoder: 2

audio:
  win_dim: 256     # <--- ADD this to reflect input window dimension

conv2:
  block: 'relu' #'skip', 'relu'
  nlayers_encoder: 4
  nlayers_embedder: 4
  nlayers_decoder: 6
  hidden_dim: 128
