dim:
  embedding: 128   # suitable transformer embedding dimension

layer:
  nlayers_encoder: 1
  nlayers_decoder: 1

audio:
  win_dim: 256     # <--- ADD this to reflect input window dimension

conv2:
  block: 'skip' #'skip', 'relu'
  layers_CE: 2
  layers_EM: 2
  hidden_dim: 64