adv: True

watermark:
  length: 10


optimize:
  gradient_scaling: True
  lr: 0.0003
  batch_size: 2
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 32
  up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
  lr_disc: 0.00002
  alpha: 10
  train_size: 31000

contrastive:
  loss_type: info_nce

iter:
  epoch: 5
  # epoch: 100
  save_circle: 5
  show_circle: 100
  val_circle: 100
